# Base docker image with all the requirements for Dreamerv3n
# docker build -f Dockerfile-base -t than6785/dreamer-base .
# docker push than6785/dreamer-base 

FROM ubuntu:24.04
#FROM vastai/ubuntu-ssh

# System
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/San_Francisco
RUN apt-get update && apt-get install -y \
  ffmpeg git vim curl software-properties-common grep \
  libglew-dev x11-xserver-utils xvfb wget nvtop \
  && apt-get clean

# Python (DMLab needs <=3.11)
ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1
ENV PIP_ROOT_USER_ACTION=ignore
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y python3.11-dev python3.11-venv && apt-get clean
RUN python3.11 -m venv /venv --upgrade-deps
ENV PATH="/venv/bin:$PATH"
RUN pip install -U pip setuptools

# Requirements
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Envs
##RUN wget -O - https://gist.githubusercontent.com/danijar/ca6ab917188d2e081a8253b3ca5c36d3/raw/install-dmlab.sh | sh
##RUN pip install ale_py==0.9.0 autorom[accept-rom-license]==0.6.1
##RUN pip install procgen_mirror
##RUN pip install crafter
RUN pip install dm_control
##RUN pip install memory_maze
##ENV MUJOCO_GL=egl
##RUN apt-get update && apt-get install -y openjdk-8-jdk && apt-get clean
##RUN pip install https://github.com/danijar/minerl/releases/download/v0.4.4-patched/minerl_mirror-0.4.4-cp311-cp311-linux_x86_64.whl
##RUN chown -R 1000:root /venv/lib/python3.11/site-packages/minerl